spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springboot2
    username: root
    password: 81754682
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  devtools:
    livereload:
      enabled: true

server:
  port: 8081
